resources
| extend planTypes = tolower('microsoft.compute/virtualmachinescalesets')
| extend type = tolower(type)
| where planTypes has type
| where  sku != "" and sku.capacity != "" and sku.capacity > 0
| extend vmcount = toint(sku.capacity)
| project subscriptionId, id, name, resourceGroup, vmcount
| extend resourceType = 'Virtual Machine Scale Set'
| extend productName = 'Defender CSPM'
| summarize count = sum(vmcount) by subscriptionId, resourceGroup, productName, resourceType
