Resources
 | where type == "microsoft.containerservice/managedclusters"
 | extend properties.agentPoolProfiles
 | extend pool = (properties.agentPoolProfiles)
 | mv-expand pool
 | extend cpuCores = toint(extract_all(@"(\d+)", tostring(split(pool.vmSize, '_')[1]))[0]) * pool.['count']
 | project subscription = subscriptionId, cluster = name, size = pool.vmSize, cpuCores, poolcount = pool.['count']
